spring:
  jpa:
    #naming:
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: configuration.SQLiteDialect #문법차이설정
        format_sql: true #Pretty print
        show_sql: true #show sql
  datasource:
    url: jdbc:sqlite:${storage_home}/boot.db
    username: racoon
    password: ""
    driverClassName: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

#mybatis
mybatis:
  config-location=classpath: mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#Slf4j
logging:
  config: classpath:logback-config.xml
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
